# Increased heap size for Gradle and Kotlin daemon
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
# Specific heap size for Kotlin daemon and increased connection timeout
kotlin.daemon.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m
kotlin.daemon.runFallbackOnCompilerDaemonError=true

android.useAndroidX=true
# Disabling Jetifier as project uses modern AndroidX libraries
android.enableJetifier=false
kotlin.code.style=official
